spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: redis-cache
  redis:
    host: localhost
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    platform: h2
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

server:
  port: 8010